spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/jpatest
    username: username
    password: secret
  config:
    import: classpath:application-local.yml
